noirart/blueprints/ajax.py
from flask import render_template, Blueprint, jsonify, current_app
from flask_login import current_user

from noirart.notifications import push_follow_notification, push_collect_notification
from noirart.models import User, Notification, Photo

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    current_app.logger.debug('ajax.py:collect()--->')
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    # if not current_user.confirmed:
    #     return jsonify(message='Confirm account required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='Already collected.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    current_app.logger.debug('ajax.py uncollect()')
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(photo)
    return jsonify(message='Collect canceled.')

noirart/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

# 默认注册用户都认证了，不用发邮件认证了，学校云服务器没连外网
# from noirart.emails import send_confirm_email, send_reset_password_email
from noirart.extensions import db
from noirart.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from noirart.models import User
from noirart.settings import Operations
from noirart.utils import generate_token, validate_token, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('Login success.', 'info')
            return redirect_back()
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        # token = generate_token(user=user, operation='confirm')
        # send_confirm_email(user=user, token=token)
        flash('Registered well done！', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


# @auth_bp.route('/confirm/<token>')
# @login_required
# def confirm(token):
#     if current_user.confirmed:
#         return redirect(url_for('main.index'))
#
#     if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
#         flash('Account confirmed.', 'success')
#         return redirect(url_for('main.index'))
#     else:
#         flash('Invalid or expired token.', 'danger')
#         return redirect(url_for('.resend_confirm_email'))
#
#
# @auth_bp.route('/resend-confirm-email')
# @login_required
# def resend_confirm_email():
#     if current_user.confirmed:
#         return redirect(url_for('main.index'))
#
#     token = generate_token(user=current_user, operation=Operations.CONFIRM)
#     send_confirm_email(user=current_user, token=token)
#     flash('New email sent, check your inbox.', 'info')
#     return redirect(url_for('main.index'))

@auth_bp.route('/forget-password', methods=['GET'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    return render_template('auth/reset_password.html')
# @auth_bp.route('/forget-password', methods=['GET', 'POST'])
# def forget_password():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.index'))
#
#     form = ForgetPasswordForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data.lower()).first()
#         if user:
#             token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
#             send_reset_password_email(user=user, token=token)
#             flash('Password reset email sent, check your inbox.', 'info')
#             return redirect(url_for('.login'))
#         flash('Invalid email.', 'warning')
#         return redirect(url_for('.forget_password'))
#     return render_template('auth/reset_password.html', form=form)


# @auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
# def reset_password(token):
#     if current_user.is_authenticated:
#         return redirect(url_for('main.index'))
#
#     form = ResetPasswordForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data.lower()).first()
#         if user is None:
#             return redirect(url_for('main.index'))
#         if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
#                           new_password=form.password.data):
#             flash('Password updated.', 'success')
#             return redirect(url_for('.login'))
#         else:
#             flash('Invalid or expired link.', 'danger')
#             return redirect(url_for('.forget_password'))
#     return render_template('auth/reset_password.html', form=form)

noirart/blueprints/main.py
import os
from flask import render_template, Blueprint, request, current_app, abort, make_response, send_from_directory, flash, \
    redirect, url_for
from flask_login import login_required, current_user
from noirart.extensions import db
from noirart.forms.main import DescriptionForm, TagForm, CommentForm
from noirart.models import Photo, Comment, Tag, Collect, Notification, Follow
from noirart.utils import rename_image, resize_image, redirect_back, flash_errors
from noirart.notifications import push_comment_notification, push_collect_notification

from noirart.decorators import permission_required
from sqlalchemy.sql.expression import func

# create main page blueprint
main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['NOIR_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/explore')
def explore():
    # print('explore()')

    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['NOIR_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


# Flask-Avatars的要求， 我们需要创建一个类似Flask内置的static视图的视图函数
# 获取小头像:<img src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


# 为了通过url就能方便获取到图片文件
# <img src="{{ url_for('main.get_image', filename=photo.filename) }}">
@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['NOIR_UPLOAD_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')  # 返回FileStorage对象
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['NOIR_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['NOIR_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['NOIR_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['NOIR_THEMES'].keys():
        abort(404)

    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30 * 24 * 60 * 60)
    return response


@main_bp.route('/photo/<int:photo_id>')
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    if page < 1:
        page = 1
    per_page = current_app.config['NOIR_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()

    description_form.description.data = photo.description
    return render_template('main/photo.html', photo=photo, comment_form=comment_form,
                           description_form=description_form, tag_form=tag_form,
                           pagination=pagination, comments=comments)


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()

    if photo_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_previous(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.asc()).first()

    if photo_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo', photo_id=photo_p.id))


@main_bp.route('/report/comment/<int:comment_id>', methods=['POST'])
@login_required
def report_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.flag += 1
    db.session.commit()
    flash('Comment reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=comment.photo_id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
def report_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo.flag += 1
    db.session.commit()
    flash('Photo reported.', 'success')
    return redirect(url_for('.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/description', methods=['POST'])
@login_required
def edit_description(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('Description updated.', 'success')

    flash_errors(form)
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/photo/<int:photo_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, photo=photo)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)
            push_comment_notification(photo_id=photo.id, receiver=comment.replied.author)
        db.session.add(comment)
        db.session.commit()
        flash('Comment published.', 'success')

        if current_user != photo.author:
            push_comment_notification(photo_id, receiver=photo.author, page=page)

    flash_errors(form)
    return redirect(url_for('.show_photo', photo_id=photo_id, page=page))


@main_bp.route('/photo/<int:photo_id>/tag/new', methods=['POST'])
@login_required
def new_tag(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter_by(name=name).first()
            if tag is None:
                tag = Tag(name=name)
                db.session.add(tag)
                db.session.commit()
            if tag not in photo.tags:
                photo.tags.append(tag)
                db.session.commit()
        flash('Tag added.', 'success')

    flash_errors(form)
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/set-comment/<int:photo_id>')
@login_required
def set_comment(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    if photo.can_comment:
        photo.can_comment = False
        flash('Comment disabled', 'info')
    else:
        photo.can_comment = True
        flash('Comment enabled.', 'info')
    db.session.commit()
    return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(

noirart/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - NoirArt</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent fixed-top my-navbar" >
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='n.png') }}" alt="NoirArt">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">

                <!-- 导航栏左侧元素 -->
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', 'Home') }}
                    {{ render_nav_item('main.explore', 'Explore') }}
                    <form class="form-inline my-2 my-lg-0">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="Photo, tag or user"
                               required>
                        <button class="btn btn-light my-2 my-sm-0" type="submit">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>

                <!-- 导航栏右侧，判断是否登陆显示不同元素 -->
                <div class="navbar-nav ml-auto">

                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.show_notifications', filter='unread') }}">
                        <span class="oi oi-bell"></span>
                        <span id="notification-badge"
                              class="{% if notification_count == 0 %}hide{% endif %} badge badge-danger badge-notification"
                              data-href="{{ url_for('ajax.notifications_count') }}">{{ notification_count }}</span>
                    </a>
                    <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="Upload">
                        <span class="oi oi-cloud-upload" ></span>&nbsp;&nbsp;
                    </a>
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            {{ current_user.name }}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <a href="{{ url_for('user.index', username=current_user.username)}}" class="dropdown-header">Logged as {{ current_user.username }}</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="bgCheck" onclick="checkboxOnclick(this)">
                                    <label class="custom-control-label" for="bgCheck">Dynamic BG</label>
                                </div>
                            </a>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>

                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Join Noir</a>
                {% endif %}
                </div>

            </div>
        </div>
    </nav>
{% endblock %}

<main style="margin-top: 60px">
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}

        <!--填充背景：视频或者图片-->
        {% if request.cookies.get('theme', 'video') == 'video' %}
        <video id="video-back" autoplay muted loop>
            <source  src="{{ url_for('static', filename='videos/bkv2.mp4') }}" type="video/mp4">
        </video>
        {% else %}
        <img id="photo-back" src="{{ url_for('static', filename='images/bk.jpg') }}">


        {% endif %}

        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>
                    &copy; 2018
                        <a href="https://github.com/youyuge34" target="_blank" title="Written by us">Leader</a> -
                        <a href="https://github.com/youyuge34/Noir_Art" target="_blank" title="Fork me on GitHub">GitHub</a> -
                        <a href="#" title="敏捷软件开发大作业">Team:敏捷工程不敏捷</a>
                    </small>

                </p>
                <p class="m-auto">

                </p>

                <p class="float-right">

                    <small>Share your design and f**k the life with us.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>

<div id="toast"></div>

{% block scripts %}

    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated = true;
        {% else %}
            var is_authenticated = false;
        {% endif %}
    </script>

    {% if request.cookies.get('theme', 'video') == 'video' %}
        <!--加载了对应的js之后才能执行里面的函数！-->
        <script> setCheckbox('video')</script>
        {% else %}
        <script> setCheckbox('photo')</script>
    {% endif %}

{% endblock %}
</body>
</html>

noirart/templates/macros.html
{% macro photo_card(photo) %}
    <div class="photo-card card card-transparent-20">
        <a class="card-thumbnail" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">
            <img class="card-img-top portrait" src="{{ url_for('main.get_image', filename=photo.filename_s) }}">
        </a>
        <div class="card-body">
            <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
        </div>
    </div>
{% endmacro %}

{% macro user_card(user) %}
    <div class="user-card text-center">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <img class="rounded avatar-m" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
        </a>
        <h6>
            <a href="{{ url_for('user.index', username=user.username) }}">{{ user.name }}</a>
        </h6>
        {{ follow_area(user) }}
    </div>
{% endmacro %}

{% macro follow_area(user) %}
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            {% if current_user.is_following(user) %}
                <form class="inline" method="post"
                      action="{{ url_for('user.unfollow', username=user.username, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-dark btn-sm">Unfollow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follow each other</p>
                    {% endif %}
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('user.follow', username=user.username, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary btn-sm">Follow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follows you</p>
                    {% endif %}
                </form>
            {% endif %}
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
{% endmacro %}